# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-03-07 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20180521_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=9, max_digits=20, null=True),
        ),
    ]
