# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-06-15 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_auto_20200514_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
