# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-06-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_auto_20200615_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='apply_flag',
            field=models.BooleanField(default=True),
        ),
    ]
