from django.conf.urls import url
from orders import views

urlpatterns = [
    url(r'^landing_sp/$', views.page_sp, name='page_sp'),
    url(r'^list/(?P<order_type>.*)/$', views.load_list, name='order_list'),
    url(r'^print_order/(?P<order_id>.*)/$', views.print_order, name='print_order'),

    url(r'^change_company/(?P<company_id>.*)/$', views.change_company_inline, name='change_company_inline'),
    url(r'^customer/$', views.change_customer_info, name='change_customer_info'),
    url(r'^change_customer/(?P<customer_id>.*)/$', views.change_customer_inline, name='change_customer_inline'),
    url(r'^change_address/$', views.change_customer_delivery_address,
        name='change_customer_delivery_address'),
    url(r'^supplier/$', views.change_supplier_info, name='change_supplier_info'),
    url(r'^change_supplier/(?P<supplier_id>.*)/$', views.change_supplier_inline, name='change_supplier_inline'),
    url(r'^order_new/(?P<order_type>.*)/(?P<style>.*)/$', views.order_new, name='order_new'),
    url(r'^order_edit/(?P<order_id>.*)/(?P<order_type>.*)/(?P<copy_id>.*)/(?P<msg>.*)/(?P<style>.*)/$', views.order_edit,
        name='order_edit'),
    url(r'^delete_order_single_row/$', views.delete_order_single_row, name='delete_order_single_row'),
    url(r'^order_delete/$', views.order_delete, name='order_delete'),
    url(r'^order_remove/(?P<order_id>.*)/(?P<order_type>.*)/(?P<style>.*)/$', views.order_remove, name='order_remove'),
    url(r'^update_do_supplier/$', views.update_do_supplier, name='update_do_supplier'),
    url(r'^create_so_from_csv/$', views.create_so_from_csv, name='create_so_from_csv'),
    url(r'^create_po_from_csv/$', views.create_po_from_csv, name='create_po_from_csv'),
    url(r'^create_gr_from_csv/$', views.create_gr_from_csv, name='create_gr_from_csv'),
    url(r'^create_do_from_csv/$', views.create_do_from_csv, name='create_do_from_csv'),
    url(r'^update_item_price/$', views.update_item_price, name='update_item_price'),
    url(r'^update_item_price_list/(?P<order_type>.*)/$', views.update_item_price_list, name='update_item_price_list'),
    url(r'^update_delivery_date/$', views.update_delivery_date, name='update_delivery_date'),
    url(r'^update_delivery_order_list/(?P<order_type>.*)/$', views.update_delivery_order_list, name='update_delivery_order_list'),
    url(r'^update_delivery_order_list_po/(?P<order_type>.*)/(?P<doc_no>.*)/$', views.update_delivery_order_list_po, name='update_delivery_order_list_po'),

    url(r'^load_tax/$', views.load_tax, name='load_tax'),
    url(r'^load_currency/$', views.load_currency, name='load_currency'),

    url(r'^generate_purchase_load/(?P<sale_order_id>.*)/$', views.generate_purchase_load,
        name='generate_purchase_load'),
    url(r'^generate_purchase_series/(?P<sale_order_id>.*)/$', views.generate_purchase_load,
        name='generate_purchase_series'),
    url(r'^search_sale_order/$', views.search_sale_order, name='search_sale_order'),
    url(r'^generate_purchase_order/$', views.generate_purchase_order, name='generate_purchase_order'),
    url(r'^load_sales_items_by_supplier/(?P<sale_order_id>.*)/(?P<supplier_id>.*)/$',
        views.load_sales_items_by_supplier,
        name='load_sales_items_by_supplier'),
    url(r'^order_view/(?P<order_id>.*)/$', views.order_view, name='order_view'),
    url(r'^good_receive_list/$', views.good_receive_list, name='good_receive_list'),
    url(r'^good_receive_new/(?P<type>.*)/$', views.good_receive_new, name='good_receive_new'),
    url(r'^change_customer_items/$', views.customer_items_search, name='change_customer_items'),
    url(r'^change_supplier_items/$', views.supplier_items_search, name='change_supplier_items'),
    url(r'^generate_good_receive/(?P<order_id>.*)/(?P<status>.*)/$', views.generate_good_receive,
        name='generate_good_receive'),
    url(r'^good_receive_search_item/$', views.good_receive_search_item, name='good_receive_search_item'),
    url(r'^good_receive_edit/(?P<order_id>.*)/(?P<type>.*)/$', views.good_receive_edit,
        name='good_receive_edit'),
    url(r'^good_receive_copy/(?P<order_id>.*)/(?P<status>.*)/$', views.good_receive_copy,
        name='good_receive_copy'),
    url(r'^order_DO_add/(?P<order_type>.*)/(?P<type>.*)/$', views.order_DO_add,
        name='order_DO_add'),
    url(r'^order_DO_edit/(?P<order_id>.*)/(?P<order_type>.*)/(?P<copy_id>.*)/(?P<type>.*)/$',
        views.order_DO_edit, name='order_DO_edit'),
    url(r'^DOInvoice_item_search/(?P<customer_id>.*)/(?P<search_condition>.*)/$',
        views.DOInvoice_item_search, name='DOInvoice_item_search'),
    url(r'^order_DO_copy/(?P<order_id>.*)/(?P<order_type>.*)/(?P<is_send>.*)/$',
        views.order_DO_copy, name='order_DO_copy'),
    url(r'^generate_DO_invoice/(?P<order_id>.*)/(?P<is_generate>.*)/(?P<is_send>.*)/$',
        views.generate_DO_invoice, name='generate_DO_invoice'),
    url(r'^list_json/(?P<order_type>.*)/$', views.OrderList__asJson, name='OrderList__asJson'),
    url(r'^gr_orderitem_list_json/$', views.good_receive_item_list_as_json, name='grList__asJson'),
    url(r'^gr_select_po_json/(?P<supplier_id>.*)/$', views.good_receive_po_as_json, name='good_receive_po_as_json'),
    url(r'^gr_select_all_po_json/(?P<supplier_id>.*)/$', views.good_receive_all_po_as_json, name='good_receive_all_po_as_json'),
    url(r'^so_orderitem_select/(?P<id_customers>.*)/(?P<item_id>.*)/$', views.soList_select__asJson, name='soList_select__asJson'),
    url(r'^so_item_supp_info/(?P<id_customers>.*)/(?P<item_id>.*)/$', views.so_item_supp_info, name='so_item_supp_info'),
    url(r'^so_items_list/(?P<id_customers>.*)/$', views.so_items_list, name='so_items_list'),
    url(r'^do_orderitem_list_json/$', views.do_invoice_item_list_as_json, name='doList__asJson'),
    url(r'^do_select_so_json/(?P<customer_id>.*)/$', views.do_by_so_as_json, name='do_by_so_as_json'),
    url(r'^do_by_all_so_as_json/(?P<customer_id>.*)/$', views.do_by_all_so_as_json, name='do_by_all_so_as_json'),
    url(r'^po_select_so_json/(?P<supplier_id>.*)/$', views.po_by_so_as_json, name='po_by_so_as_json'),
    url(r'^po_by_so_all_data_json/(?P<supplier_id>.*)/$', views.po_by_so_all_data_json, name='po_by_so_all_data_json'),

    url(r'^so_orderitem_list_json/$', views.so_invoice_item_list_as_json, name='soList__asJson'),
    url(r'^po_orderitem_list_json/$', views.po_invoice_item_list_as_json, name='poList__asJson'),

    url(r'^apache_output_json/$', views.apache_output_json, name='apache_output_json'),

    url(r'^po_select_list_json/(?P<id_supplier>.*)/$', views.po_select_as_json, name='po_select_as_json'),
    url(r'^customer_search_by_code/$', views.customer_search_by_code, name='customer_search_by_code'),
    url(r'^supplier_search_by_code/$', views.supplier_search_by_code, name='supplier_search_by_code'),
    url(r'^suppliers_list_as_json/$', views.suppliers_list_as_json, name='suppliers_list_as_json'),
    url(r'^customers_list_as_json/$', views.customers_list_as_json, name='customers_list_as_json'),
    url(r'^is_doc_no_exist/$', views.is_doc_no_exist, name='is_doc_no_exist'),
    url(r'^get_orderitems_by_so_no/$', views.get_orderitems_by_so_no, name='get_orderitems_by_so_no'),
    url(r'^get_so_orderitems_for_po/$', views.get_so_orderitems_for_po, name='get_so_orderitems_for_po'),
    url(r'^get_orderitems_by_cust_po_no/$', views.get_orderitems_by_cust_po_no, name='get_orderitems_by_cust_po_no'),
    url(r'^get_orderitems_by_po_no/$', views.get_orderitems_by_po_no, name='get_orderitems_by_po_no'),
    url(r'^download_purchase_load/$', views.download_purchase_load, name='download_purchase_load'),
    url(r'^download_purchase_order/$', views.download_purchase_order, name='download_purchase_order'),
    url(r'^download_delivery_order/(?P<order_id>.*)/$', views.download_delivery_order, name='download_delivery_order'),
    url(r'^generate_DO_load/(?P<good_receive_id>.*)/$', views.generate_DO_load, name='generate_DO_load'),
    url(r'^load_sales_items_by_customer/(?P<good_receive_id>.*)/(?P<reference_id>.*)/$',
        views.load_sales_items_by_customer, name='load_sales_items_by_customer'),
    url(r'^generate_DO_from_GR/(?P<good_receive_id>.*)/$', views.generate_DO_from_GR, name='generate_DO_from_GR'),
    url(r'^documents_list_as_json/$', views.documents_list_as_json, name='documents_list_as_json'),
    url(r'^customer_json_for_AR/$', views.customer_json_for_AR, name='customer_json_for_AR'),
    url(r'^get_orderitems_by_code/$', views.get_items_by_code, name='get_orderitems_by_code'),
    url(r'^sale_debit_credit_note/(?P<order_type>.*)/(?P<status>.*)/$', views.sale_debit_credit_note_new,
        name='sale_debit_credit_note'),
    url(r'^purchase_crdb_note_add/(?P<status>.*)/$', views.purchase_crdb_note_add,
        name='purchase_crdb_note_add'),
    url(r'^purchase_crdb_note_edit/(?P<order_id>.*)/(?P<status>.*)/$', views.purchase_crdb_note_edit,
        name='purchase_crdb_note_edit'),
    url(r'^sale_debit_credit_note_edit/(?P<order_id>.*)/(?P<order_type>.*)/(?P<copy_id>.*)/(?P<is_send>.*)/$',
        views.sale_debit_credit_note_edit, name='sale_debit_credit_note_edit'),
    url(r'^load_grList__asJson/$', views.load_grList__asJson, name='load_grList__asJson'),
    url(r'^load_doList__asJson/$', views.load_doList__asJson, name='load_doList__asJson'),
    url(r'^get_orderitems_by_gr_no/$', views.get_orderitems_by_gr_no, name='get_orderitems_by_gr_no'),
    url(r'^get_orderitems_by_do_no/$', views.get_orderitems_by_do_no, name='get_orderitems_by_do_no'),
    url(r'^detail_order/(?P<order_id>.*)/(?P<order_type>.*)/$', views.expanded_order, name='expanded_order'),
    url(r'^get_item_backorder/$', views.get_item_backorder, name='get_item_backorder'),
    url(r'^location_code_list/$', views.location_code_list, name='location_code_list'),
    url(r'^check_so_po_reference/(?P<reference_id>.*)/(?P<order_type>.*)/$', views.check_so_po_reference,
        name='check_so_po_reference'),
    url(r'^check_quantity_po_so_reference/(?P<reference_id>.*)/(?P<order_type>.*)/(?P<refer_line>.*)/$', views.check_quantity_po_so_reference,
        name='check_quantity_po_so_reference'),

    url(r'^get_so_order_item_for_po/$', views.get_so_order_item_for_po, name='get_so_order_item_for_po'),
    url(r'^get_order_item_by_po_no/$', views.get_order_item_by_po_no, name='get_order_item_by_po_no'),
    url(r'^get_order_item_by_so_no/$', views.get_order_item_by_so_no, name='get_order_item_by_so_no'),

    url(r'^export_part_purchase_price/$', views.export_part_purchase_price, name='export_part_purchase_price'),
    url(r'^export_part_purchase_price_file/$', views.export_part_purchase_price_file, name='export_part_purchase_price_file'),

    url(r'^export_part_sales_price/$', views.export_part_sales_price, name='export_part_sales_price'),
    url(r'^export_part_sales_price_file/$', views.export_part_sales_price_file, name='export_part_sales_price_file'),
    url(r'^download_snp_template/(?P<order_type>.*)/$', views.download_snp_template, name='download_snp_template'),
]
