# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('number', models.IntegerField(null=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('shortname', models.CharField(max_length=30, null=True)),
                ('tax_type', models.IntegerField(default=1)),
                ('ytd', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('mtd', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('ytdoc', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('mtdoc', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('distribution_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_code', to='accounts.DistributionCode')),
                ('tax_account_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_account_code', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='TaxAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('retainage_rpt_type', models.CharField(choices=[('1', 'No Reporting'), ('2', 'At Time of Retainage Document'), ('3', 'At Time of Original Document')], max_length=50, null=True)),
                ('max_tax_allowable', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('no_tax_charged_below', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('tax_base', models.CharField(choices=[('1', 'Selling price'), ('2', 'Standard cost'), ('3', 'Most recent cost'), ('4', 'Alternate amount 1'), ('5', 'Alternate amount 2')], max_length=50, null=True)),
                ('report_level', models.CharField(choices=[('1', 'At invoice level'), ('2', 'No reporting')], max_length=50, null=True)),
                ('is_recoverable', models.BooleanField(default=False)),
                ('recoverable_rate', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('is_expense_separately', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_account', to='accounts.Account')),
                ('liability_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liability_account', to='accounts.Account')),
                ('recoverable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recoverable_account', to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('transaction_type', models.CharField(choices=[('1', 'Sales'), ('2', 'Purchases')], max_length=50, null=True)),
                ('calculation_method', models.CharField(choices=[('1', 'Calculate tax by summary'), ('2', 'Calculate tax by detail')], max_length=50, null=True)),
                ('is_taxable', models.BooleanField(default=False)),
                ('is_surtax', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
                ('surtax_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surtax_authority', to='taxes.TaxAuthority')),
                ('surtax_authority_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('tax_authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_authority', to='taxes.TaxAuthority')),
            ],
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxes.TaxAuthority'),
        ),
        migrations.AddField(
            model_name='tax',
            name='tax_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxes.TaxGroup'),
        ),
    ]
