# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxes', '0001_initial'),
        ('countries', '0001_initial'),
        ('companies', '0002_auto_20180215_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, null=True)),
                ('short_description', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('sale_price', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('purchase_price', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('stockist_price', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('cost_price', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('retail_price', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('last_purchase_price', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('last_purchase_doc', models.CharField(max_length=50, null=True)),
                ('last_purchase_date', models.DateField(null=True)),
                ('minimun_order', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('size', models.CharField(max_length=50, null=True)),
                ('weight', models.CharField(max_length=50, null=True)),
                ('po_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('so_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('backorder_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('in_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('out_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('balance_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('par_value', models.CharField(max_length=50, null=True)),
                ('book_value', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('move_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('model_qty', models.IntegerField(null=True)),
                ('person_incharge', models.CharField(max_length=500, null=True)),
                ('ratio', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True)),
                ('short_description', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('type', models.IntegerField(null=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxes.Tax')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='items.ItemCategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_id', to='countries.Country'),
        ),
    ]
