# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('items', '0002_item_default_location'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='default_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_default_supplier', to='suppliers.Supplier'),
        ),
        migrations.AddField(
            model_name='item',
            name='inv_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_measure', to='items.ItemMeasure'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_currency', to='currencies.Currency'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_measure', to='items.ItemMeasure'),
        ),
        migrations.AddField(
            model_name='item',
            name='report_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_measure', to='items.ItemMeasure'),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_currency', to='currencies.Currency'),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_measure', to='items.ItemMeasure'),
        ),
    ]
