# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-18 03:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20180215_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='move_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
