# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-11-26 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20190621_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='itemmeasure',
            name='code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
