version: 0.0
os: linux
files:
 - source: /
   destination: /home/ec2-user/deploy/ikary
hooks:
 BeforeInstall:
   - location: deploy/before_install_rel.sh
     timeout: 300
     runas: ec2-user
 AfterInstall:
   - location: deploy/after_install.sh
     timeout: 300
     runas: ec2-user
 ApplicationStart:
   - location: deploy/server_start_rel.sh
     timeout: 3000
     runas: ec2-user
