# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('items', '0002_item_default_location'),
        ('locations', '0001_initial'),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_date', models.DateField(default=datetime.date.today)),
                ('invoice_date', models.DateField(default=datetime.date.today)),
                ('delivery_date', models.DateField(default=datetime.date.today, null=True)),
                ('order_code', models.CharField(max_length=50, null=True)),
                ('document_number', models.CharField(max_length=50, null=True)),
                ('transport_responsibility', models.CharField(max_length=100, null=True)),
                ('reference_number', models.CharField(max_length=50, null=True)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('status', models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Sent'), (3, 'Received'), (4, 'Delivered'), (6, 'Partial'), (0, 'Undefined')], null=True)),
                ('discount', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('subtotal', models.DecimalField(decimal_places=6, max_digits=20)),
                ('total', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('balance', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('order_type', models.SmallIntegerField(choices=[(1, 'SALES ORDER'), (2, 'PURCHASE ORDER'), (3, 'SALES DEBIT NOTE'), (4, 'SALES CREDIT NOTE'), (5, 'PURCHASE INVOICE'), (6, 'SALES INVOICE'), (7, 'PURCHASE DEBIT NOTE'), (8, 'PURCHASE CREDIT NOTE'), (9, 'PURCHASE CR DB NOTE'), (10, 'SALES CR DB NOTE'), (998, 'UPDATE SALES STATUS'), (999, 'UPDATE PURCHASE STATUS'), (1000, 'UPDATE S&P STATUS')], null=True)),
                ('header_text', models.CharField(max_length=4000, null=True)),
                ('footer', models.CharField(max_length=4000, null=True)),
                ('note', models.CharField(max_length=4000, null=True)),
                ('remark', models.CharField(max_length=4000, null=True)),
                ('packing_number', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('is_hidden', models.BooleanField(default=False)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('is_confirm', models.CharField(max_length=2, null=True)),
                ('document_type', models.CharField(choices=[('D', 'D/O'), ('I', 'Invoice'), ('B', 'D/O and Invoice')], default='B', max_length=1, null=True)),
                ('tax_exchange_rate', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('supllier_exchange_rate', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('via', models.CharField(max_length=100, null=True)),
                ('exchange_rate_date', models.DateField(null=True)),
                ('payment_term', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('note_1', models.TextField(blank=True, null=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.IntegerField()),
                ('y_position', models.IntegerField()),
                ('label', models.CharField(blank=True, max_length=300, null=True)),
                ('value', models.CharField(blank=True, max_length=300, null=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('line_number', models.IntegerField(null=True)),
                ('refer_line', models.CharField(max_length=11, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=9, null=True)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('delivery_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('receive_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('return_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('bkord_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('customer_po_no', models.CharField(max_length=50, null=True)),
                ('refer_code', models.CharField(max_length=50, null=True)),
                ('refer_number', models.CharField(max_length=50, null=True)),
                ('wanted_date', models.DateField(null=True)),
                ('schedule_date', models.DateField(null=True)),
                ('last_receive_date', models.DateField(null=True)),
                ('last_delivery_date', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('carton_no', models.CharField(max_length=50, null=True)),
                ('carton_total', models.IntegerField(default=0, null=True)),
                ('pallet_no', models.CharField(max_length=50, null=True)),
                ('net_weight', models.DecimalField(decimal_places=6, default=0, max_digits=12, null=True)),
                ('m3_number', models.DecimalField(decimal_places=4, default=0, max_digits=9, null=True)),
                ('description', models.TextField(null=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('is_hidden', models.BooleanField(default=False)),
                ('last_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('last_purchase_price', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('from_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_from_currency', to='currencies.Currency')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('origin_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_id', to='orders.Order')),
            ],
        ),
    ]
