# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-21 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdelivery_attention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='m3_number',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, null=True),
        ),
    ]
