# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-06-15 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190621_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='supllier_exchange_rate',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_exchange_rate',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
