# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-08-19 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200615_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='m3_number',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='net_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, null=True),
        ),
    ]
