# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-09-28 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201026_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='bkord_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='last_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='receive_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='return_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
