# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('companies', '0002_auto_20180215_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=20, null=True)),
                ('postal_code', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
                ('credit_limit', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('payment_term', models.CharField(max_length=10, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('fax', models.CharField(max_length=20, null=True)),
                ('note1', models.TextField(null=True)),
                ('note2', models.TextField(null=True)),
                ('note3', models.TextField(null=True)),
                ('customer_type', models.IntegerField(default=0, null=True)),
                ('pricing_type', models.CharField(default=0, max_length=10, null=True)),
                ('interest_flag', models.CharField(default=0, max_length=10, null=True)),
                ('statement', models.CharField(default=0, max_length=10, null=True)),
                ('interest_1', models.DecimalField(decimal_places=5, default=0, max_digits=20, null=True)),
                ('interest_2', models.DecimalField(decimal_places=5, default=0, max_digits=20, null=True)),
                ('interest_3', models.DecimalField(decimal_places=5, default=0, max_digits=20, null=True)),
                ('interest_4', models.DecimalField(decimal_places=5, default=0, max_digits=20, null=True)),
                ('interest_5', models.DecimalField(decimal_places=5, default=0, max_digits=20, null=True)),
                ('accode_ar', models.CharField(default=0, max_length=20, null=True)),
                ('accode_sal', models.CharField(default=0, max_length=20, null=True)),
                ('accode_exc', models.CharField(default=0, max_length=20, null=True)),
                ('accode_int', models.CharField(default=0, max_length=20, null=True)),
                ('accode_bnk', models.CharField(default=0, max_length=20, null=True)),
                ('accode_chr', models.CharField(default=0, max_length=20, null=True)),
                ('center_ar', models.CharField(default=0, max_length=20, null=True)),
                ('center_sal', models.CharField(default=0, max_length=20, null=True)),
                ('center_exc', models.CharField(default=0, max_length=20, null=True)),
                ('center_int', models.CharField(default=0, max_length=20, null=True)),
                ('center_bnk', models.CharField(default=0, max_length=20, null=True)),
                ('center_chr', models.CharField(default=0, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('email_msg', models.CharField(default='                                                                    COMPANY_NAME\n\n\nDATE                                                                                                                  \n\n\nDear CUSTOMER_NAME,\n\n\nIt has come to our attention that a portion of the balance of your account has long been outstanding; that is a total of AMOUNT_CURRENCY OUTSTANDING_AMOUNT has been outstanding for more than DAYS_OVERDUE days.\n\nWe wish to point out that our terms of payment are met CUS_PAYMENT_TERM days, and, if this unpaid amount is not cleared up immediately, we will be forced to initiate legal action.\n\nYours Sincerely,\n\n\nCredit Manager\nCOMPANY_NAME\n\n', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_price', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('new_price', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('leading_days', models.CharField(max_length=500, null=True)),
                ('effective_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('attention', models.CharField(max_length=500, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('fax', models.CharField(max_length=20, null=True)),
                ('note_1', models.CharField(max_length=4000, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
