# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20180215_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_msg',
            field=models.CharField(default='                                                                    COMPANY_NAME\n\n\nDATE\n\n\nDear CUSTOMER_NAME,\n\n\nIt has come to our attention that a portion of the balance of your account has long been outstanding; that is a total of AMOUNT_CURRENCY OUTSTANDING_AMOUNT has been outstanding for more than DAYS_OVERDUE days.\n\nWe wish to point out that our terms of payment are met CUS_PAYMENT_TERM days, and, if this unpaid amount is not cleared up immediately, we will be forced to initiate legal action.\n\nYours Sincerely,\n\n\nCredit Manager\nCOMPANY_NAME\n\n', max_length=1000, null=True),
        ),
    ]
