# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-21 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20190606_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='interest_1',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='interest_2',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='interest_3',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='interest_4',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='interest_5',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True),
        ),
    ]
