# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-05-13 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20190621_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
