# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_auto_20180215_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('io_flag', models.CharField(choices=[('1', 'IN'), ('2', 'Transfer'), ('3', 'OUT')], max_length=50, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, null=True)),
                ('line_number', models.IntegerField(null=True)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('out_qty', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('balance_qty', models.IntegerField(default=0)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_history', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=50, null=True)),
                ('line_number', models.IntegerField(null=True)),
                ('sales_date', models.DateField(default=datetime.date.today)),
                ('out_qty', models.IntegerField(default=0)),
                ('in_qty', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('ref_line', models.IntegerField(null=True)),
                ('ref_no', models.CharField(max_length=50, null=True)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('document_line', models.IntegerField(null=True)),
                ('sales_price', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_history', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_date', models.DateField(default=datetime.date.today)),
                ('document_number', models.CharField(max_length=50, null=True)),
                ('io_flag', models.CharField(choices=[('1', 'IN'), ('2', 'Transfer'), ('3', 'OUT')], max_length=50, null=True)),
                ('price_flag', models.CharField(choices=[('1', 'PURCHASE'), ('2', 'STOCKLIST'), ('3', 'RETAIL')], max_length=50, null=True)),
                ('doc_type', models.CharField(choices=[('0', 'Order'), ('1', 'DO/Invoice'), ('2', 'Sales D/N'), ('3', 'Sales C/N'), ('4', 'Purchase D/N'), ('5', 'Purchase C/N'), ('6', 'Inventory')], max_length=50, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Draft'), (2, 'Sent'), (3, 'Received'), (4, 'Delivered'), (6, 'Partial'), (0, 'Undefined')], null=True)),
                ('remark', models.CharField(max_length=4000, null=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('closing_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_from_sp', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('outstanding_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('cost_price', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('remark', models.TextField(null=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('io_flag', models.CharField(choices=[('1', 'IN'), ('2', 'Transfer'), ('3', 'OUT')], max_length=50, null=True)),
                ('price_flag', models.CharField(choices=[('1', 'PURCHASE'), ('2', 'STOCKLIST'), ('3', 'RETAIL')], max_length=50, null=True)),
                ('doc_type', models.CharField(choices=[('0', 'Order'), ('1', 'DO/Invoice'), ('2', 'Sales D/N'), ('3', 'Sales C/N'), ('4', 'Purchase D/N'), ('5', 'Purchase C/N'), ('6', 'Inventory')], max_length=50, null=True)),
                ('auto_generate', models.BooleanField()),
                ('ics_prefix', models.CharField(max_length=10, null=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('menu_type', models.CharField(max_length=2, null=True)),
                ('last_no', models.IntegerField(default=0)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
