# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_auto_20180215_1454'),
        ('items', '0002_item_default_location'),
        ('locations', '0001_initial'),
        ('companies', '0002_auto_20180215_1454'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='out_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_location', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='transaction_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.TransactionCode'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_location', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='ref_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_code', to='inventory.TransactionCode'),
        ),
        migrations.AddField(
            model_name='outgoing',
            name='transaction_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.TransactionCode'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_location', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='incoming',
            name='transaction_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.TransactionCode'),
        ),
        migrations.AddField(
            model_name='history',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='history',
            name='item_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
        migrations.AddField(
            model_name='history',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_location', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='history',
            name='transaction_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.TransactionCode'),
        ),
    ]
