# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('description', models.TextField(null=True)),
                ('debit_amount', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20)),
                ('credit_amount', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=20)),
                ('account_type', models.CharField(choices=[('2', 'Balance Sheet'), ('3', 'Retained Earning'), ('1', 'Income Statement')], max_length=1, null=True)),
                ('balance_type', models.CharField(choices=[('1', 'Debit'), ('2', 'Credit')], max_length=1, null=True)),
                ('is_multicurrency', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.CharField(max_length=10, null=True)),
                ('period_year', models.CharField(max_length=10, null=True)),
                ('period_date', models.DateField()),
                ('source_debit_amount', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('source_credit_amount', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('source_net_change', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('source_begin_balance', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('source_end_balance', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('functional_debit_amount', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('functional_credit_amount', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('functional_net_change', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('functional_begin_balance', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('functional_end_balance', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('1', 'AR Account Set'), ('2', 'AP Account Set')], max_length=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=20, null=True)),
                ('is_debit', models.BooleanField(default=True)),
                ('is_credit', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('1', 'Accounting Group'), ('2', 'Balance Sheet Group'), ('3', 'Profit and Loss Group')], default='1', max_length=1)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DistributionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('1', 'AR Distribution Code'), ('2', 'AP Distribution Code')], max_length=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReportGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code_text', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('report_template_type', models.CharField(choices=[('0', 'Profit & Loss'), ('1', 'Balance Sheet')], max_length=2, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevaluationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('rate_type', models.CharField(max_length=2, null=True)),
                ('source_type', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
