# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-20 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_use_segment'),
        ('accounts', '0002_auto_20180215_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='segment_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.CostCenters'),
        ),
    ]
