# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180215_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountset',
            name='discount_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountset_discount_account', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='accountset',
            name='prepayment_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountset_prepayment_account', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='accountset',
            name='writeoff_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountset_writeoff_account', to='accounts.Account'),
        ),
    ]
