# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-21 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_segment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_segment',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
