# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-27 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_account_segment'),
        ('accounts', '0003_auto_20180215_1704'),
    ]

    operations = [
    ]
