# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-18 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcurrency',
            name='revaluation_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AccountCurrency_revaluation_code', to='accounts.RevaluationCode'),
        ),
    ]
