# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-04 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180418_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcurrency',
            name='revaluation_account',
        ),
    ]
