# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-18 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_accountcurrency_revaluation_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
