# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-04 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191018_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_segment',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
