# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-21 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_auto_20190307_1005'),
        ('accounts', '0009_auto_20191204_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_specific_currency',
            field=models.BooleanField(default=False),
        ),
    ]
