# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-10-16 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191221_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deactivate_date',
            field=models.DateField(null=True),
        ),
    ]
