# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-11-19 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_deactivate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deactivate_period',
            field=models.DateField(null=True),
        ),
    ]
