from django.conf.urls import url
from suppliers import views

urlpatterns = [
    url(r'^$', views.load_list, name='index'),
    url(r'^list/$', views.load_list, name='supplier_list'),
    url(r'^add/$', views.supplier_add, name='supplier_add'),
    # url(r'^edit/(?P<supplier_id>\d+)/(?P<active_tab_index>\d+)/$', views.supplier_edit, name='supplier_edit'),
    url(r'^edit/(?P<supplier_id>\d+)/$', views.supplier_edit, name='supplier_edit'),
    url(r'^delete/(?P<supplier_id>\d+)/(?P<page>\d+)/$', views.supplier_delete, name='supplier_delete'),
    url(r'^supplier_item_list/$', views.supplier_item_list, name='supplier_item_list'),
    url(r'^item_by_supplier/(?P<supplier_id>.*)/$', views.item_by_supplier, name='item_by_supplier'),
    # url(r'^supplier_item_add/$', views.supplier_item_add, name='supplier_item_add'),
    url(r'^get_by_pk/(?P<supp_id>\d+)/$', views.supplier_By_pk, name='supplier_By_pk'),
    url(r'^get_by_code/(?P<supplier_code>.*)/$', views.supplier_By_code, name='supplier_By_code'),
    url(r'^item_add/(?P<supplier_id>\d+)/$', views.item_add, name='supplier_add_item'),
    url(r'^item_edit/(?P<supplieritem_id>\d+)/$', views.item_edit, name='supplier_edit_item'),
    url(r'^item_delete/(?P<supplieritem_id>\d+)/$', views.item_delete, name='supplier_delete_item'),
    url(r'^list/pagination$', views.SupplierList__asJson, name='SupplierList__asJson'),
    url(r'^item_add/(?P<supplier_id>.*)/pagination$', views.SupplierItemList__asJson, name='SupplierItemList__asJson'),
    url(r'^item_edit/(?P<supplieritem_id>.*)/pagination$', views.SupplierEditItemList__asJson,
        name='SupplierEditItemList__asJson'),
    url(r'^item_add/getiteminfo$', views.get_item_info, name='get_item_info'),
    url(r'^acc_vendor_list/$', views.account_vendor_list, name='acc_vendor_list'),
    url(r'^get_supplier_code_list/$', views.get_supplier_code_list, name='get_supplier_code_list'),
    url(r'^acc/$', views.acc_Vendor_add, name='acc_Vendor_add'),
    url(r'^acc_edit/(?P<supplier_id>\d+)/$', views.acc_vendor_edit, name='acc_vendor_edit'),
    url(r'^bank_list/$', views.SBankList__asJson, name='SBankList__asJson'),
    url(r'^load_bank_set/$', views.load_bank_set, name='load_bank_set'),
    url(r'^load_dis_code/$', views.load_dis_code, name='load_dis_code'),
    url(r'^load_tax_code/$', views.load_tax_code, name='load_tax_code'),
    url(r'^acc_vendor_list/pagination$', views.AccountSupplierList__asJson, name='AcountSupplierList__asJson'),
    url(r'^country_set_list/$', views.CountrySetList__asJson, name='Supplier__CountrySetList__asJson'),
    url(r'^account_set_list/$', views.AP_AccountSetList__asJson, name='Supplier__AccountSetList__asJson'),
    url(r'^tax_set_list/$', views.TaxSetList__asJson, name='Supplier__TaxSetList__asJson'),
]
