# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180215_1454'),
        ('accounting', '0003_auto_20180215_1454'),
        ('companies', '0002_auto_20180215_1454'),
        ('taxes', '0001_initial'),
        ('currencies', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_credit_account', models.BooleanField(default=False)),
                ('is_debit_account', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('remark', models.TextField(null=True)),
                ('number', models.CharField(max_length=50, null=True)),
                ('source_type', models.CharField(choices=[('GL-AD', 'Audit Adjustments (G/L Entry)'), ('GL-CL', 'G/L Closing Entry'), ('GL-JE', 'G/L Journal Entry'), ('GL-RV', 'G/L Revaluation Transactions'), ('GL-CV', 'G/L Data Conversion Entry'), ('AP-AD', 'A/P Adjustments'), ('AP-CR', 'A/P Credit Note'), ('AP-DB', 'A/P Debit Note'), ('AP-GL', 'A/P Revaluation'), ('AP-IN', 'A/P Invoice'), ('AP-PY', 'A/P Check'), ('AP-RD', 'A/P Rounding'), ('AP-RV', 'A/P Revaluation'), ('AR-AD', 'A/R Adjustments'), ('AR-CR', 'A/R Credit Note'), ('AR-DB', 'A/R Debit Note'), ('AR-GL', 'A/R Revaluation'), ('AR-IN', 'A/R Invoice'), ('AR-PY', 'A/R Payment Received'), ('AR-RD', 'A/R Rounding'), ('AR-RV', 'A/R Revaluation')], max_length=50, null=True)),
                ('reference', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('functional_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('rate_date', models.DateField(null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=7, default=1, max_digits=20)),
                ('is_tax_include', models.BooleanField(default=False)),
                ('is_tax_transaction', models.BooleanField(default=False)),
                ('is_close', models.BooleanField(default=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('functional_balance_type', models.CharField(choices=[('1', 'Debit'), ('2', 'Credit')], max_length=1, null=True)),
                ('is_report', models.BooleanField(default=False)),
                ('is_clear_tax', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
                ('distribution_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DistributionCode')),
                ('functional_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functional_currency', to='currencies.Currency')),
                ('journal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='accounting.Journal')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('is_debit', models.BooleanField(default=True)),
                ('is_credit', models.BooleanField(default=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.TransactionMethod'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_transactions', to='transactions.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_invoice', to='accounting.Journal'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxes.Tax'),
        ),
    ]
