# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-07-23 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20180215_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='base_tax_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True),
        ),
    ]
