# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-29 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_base_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_manual_tax_input',
            field=models.BooleanField(default=False),
        ),
    ]
