# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-18 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20200615_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_journal_outstanding',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
