# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-10-21 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20211020_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_auto_exch',
            field=models.BooleanField(default=False),
        ),
    ]
