# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('is_category', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=datetime.date.today, null=True)),
                ('update_date', models.DateField(default=datetime.date.today, null=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('report_pdf', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/christlestario/project/ikari/src/ikari/media/'), upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_category', to='reports.Report')),
            ],
        ),
    ]
