# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-06 01:03
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/kelvin/Projects/ikary/src/ikari/media/'), upload_to=''),
        ),
    ]
