# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-25 23:59
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190606_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/admin/Projects/ikary/src/ikari/media/'), upload_to=''),
        ),
    ]
