# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-05-24 09:01
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20220505_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/smzakaria/dev/ikari/ikary/src/ikari/media/'), upload_to=''),
        ),
    ]
