# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('customers', '0001_initial'),
        ('accounting', '0002_auto_20180215_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_customer', to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='journal',
            name='exchange_rate_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.ExchangeRate'),
        ),
    ]
