# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180215_1454'),
        ('suppliers', '0001_initial'),
        ('accounting', '0003_auto_20180215_1454'),
        ('companies', '0002_auto_20180215_1454'),
        ('taxes', '0001_initial'),
        ('currencies', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='journal',
            name='orig_exch_rate_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orig_exch_rate_fk', to='currencies.ExchangeRate'),
        ),
        migrations.AddField(
            model_name='journal',
            name='original_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_currency', to='currencies.Currency'),
        ),
        migrations.AddField(
            model_name='journal',
            name='payment_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_refer_account', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='journal',
            name='payment_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.PaymentCode'),
        ),
        migrations.AddField(
            model_name='journal',
            name='payment_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_currency', to='currencies.Currency'),
        ),
        migrations.AddField(
            model_name='journal',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_supplier', to='suppliers.Supplier'),
        ),
        migrations.AddField(
            model_name='journal',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxes.Tax'),
        ),
        migrations.AddField(
            model_name='fiscalcalendar',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='batch',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='batch',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency'),
        ),
    ]
