# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('accounting', '0004_auto_20180215_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringentry',
            name='exch_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.ExchangeRate'),
        ),
    ]
