# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-16 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_recurringentry_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringentry',
            name='expire_date',
            field=models.DateField(null=True),
        ),
    ]
