# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-23 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
        ('accounts', '0002_auto_20180215_1454'),
        ('customers', '0003_auto_20180215_1454'),
        ('banks', '0004_bank_supplier'),
        ('currencies', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('accounting', '0007_auto_20180216_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringentry',
            name='account_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_entry_journal_account_set', to='accounts.AccountSet'),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.Bank'),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency'),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_entry_journal_customer', to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='document_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='document_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='document_type',
            field=models.CharField(choices=[('1', 'Invoice'), ('2', 'Debit Note'), ('3', 'Credit Note'), ('4', 'Interest')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='invoice_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='is_manual_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='journal_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='name',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='order_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='original_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='original_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_entry_original_currency', to='currencies.Currency'),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='paid_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='payment_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_entry_payment_refer_account', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='payment_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='payment_check_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='payment_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.PaymentCode'),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='payment_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_entry_journal_currency', to='currencies.Currency'),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='payment_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='po_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='posting_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='reference',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_entry_journal_supplier', to='suppliers.Supplier'),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxes.Tax'),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='tax_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='transaction_type',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='applied_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='distribution_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DistributionCode'),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='document_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='document_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='document_type',
            field=models.CharField(choices=[('1', 'Invoice'), ('2', 'Debit Note'), ('3', 'Credit Note'), ('4', 'Interest')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='is_tax_include',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='is_tax_transaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='net_balance',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='original_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='payment_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='pending_balance',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='related_invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_related_invoice', to='accounting.Journal'),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='remark',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxes.Tax'),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='tax_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentrydetail',
            name='total_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
