# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-26 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20180215_1609'),
        ('accounting', '0007_auto_20180216_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='adjustment_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='journal',
            name='discount_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='journal',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='transactions.Transaction'),
        ),
    ]
