# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-23 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('accounting', '0009_auto_20180226_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringentry',
            name='orig_exch_rate',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='orig_exch_rate_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_orig_exch_rate_fk', to='currencies.ExchangeRate'),
        ),
    ]
