# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-27 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20180223_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringentrydetail',
            name='discount_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
