# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-01 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20180227_1014'),
        ('accounting', '0008_auto_20180223_1444'),
    ]

    operations = [
    ]
