# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-08 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_recurringentry_re_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringentry',
            name='perd_year',
            field=models.IntegerField(default=0),
        ),
    ]
