# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-28 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_recurringentry_perd_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='posting_sequence',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
