# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-29 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_auto_20180328_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringentrydetail',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
    ]
