# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-24 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_recurringentrydetail_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='is_auto_reversed_entry',
            field=models.BooleanField(default=False),
        ),
    ]
