# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-05-17 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_auto_20180517_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='rev_perd_year',
            field=models.IntegerField(default=0),
        ),
    ]
