# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-02 08:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_merge'),
        ('currencies', '0003_auto_20190307_1005'),
        ('accounting', '0023_auto_20190524_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevaluationLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_type', models.IntegerField(default=0)),
                ('revaluation_date', models.DateField(default=datetime.date.today)),
                ('exchange_rate', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('rate_date', models.DateField(default=datetime.date.today, null=True)),
                ('rate_type', models.CharField(choices=[('AV', 'Monthly Average Rate'), ('SP', 'Daily Spot Rate'), ('SR', 'Source Rate'), ('TA', 'Financial Trnslation-Average'), ('TR', 'Financial Trnslation-Current')], max_length=50, null=True)),
                ('posting_sequence', models.CharField(max_length=50, null=True)),
                ('posting_date', models.DateField(default=datetime.date.today, null=True)),
                ('revaluation_method', models.IntegerField(default=0, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
            ],
        ),
        migrations.AlterField(
            model_name='batch',
            name='document_type',
            field=models.CharField(choices=[('1', 'Invoice'), ('2', 'Debit Note'), ('3', 'Credit Note'), ('4', 'Interest'), ('5', 'Unapplied Cash'), ('6', 'Prepayment'), ('7', 'Receipt'), ('8', 'Refund'), ('9', 'Payment'), ('10', 'Adjustment')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='journal',
            name='document_type',
            field=models.CharField(choices=[('1', 'Invoice'), ('2', 'Debit Note'), ('3', 'Credit Note'), ('4', 'Interest'), ('5', 'Unapplied Cash'), ('6', 'Prepayment'), ('7', 'Receipt'), ('8', 'Refund'), ('9', 'Payment'), ('10', 'Adjustment')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='recurringentry',
            name='document_type',
            field=models.CharField(choices=[('1', 'Invoice'), ('2', 'Debit Note'), ('3', 'Credit Note'), ('4', 'Interest'), ('5', 'Unapplied Cash'), ('6', 'Prepayment'), ('7', 'Receipt'), ('8', 'Refund'), ('9', 'Payment'), ('10', 'Adjustment')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='recurringentrydetail',
            name='document_type',
            field=models.CharField(choices=[('1', 'Invoice'), ('2', 'Debit Note'), ('3', 'Credit Note'), ('4', 'Interest'), ('5', 'Unapplied Cash'), ('6', 'Prepayment'), ('7', 'Receipt'), ('8', 'Refund'), ('9', 'Payment'), ('10', 'Adjustment')], default='0', max_length=2),
        ),
    ]
