# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-10 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20190730_1639'),
        ('customers', '0005_auto_20190621_1132'),
        ('accounting', '0024_auto_20190902_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevaluationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.CharField(max_length=50, null=True)),
                ('source_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('prior_rate', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('rev_rate', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
                ('prior_functional', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('new_functional', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('gain_loss', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.RevaluationLogs')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier')),
            ],
        ),
    ]
