# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-11 01:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_revaluationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='revaluationdetails',
            name='document_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='revaluationdetails',
            name='due_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
