# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-31 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20191222_1401'),
        ('accounting', '0026_auto_20190911_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=10)),
                ('transaction_type', models.CharField(max_length=100)),
                ('transaction_field', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='GLIntegrationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_0', models.CharField(max_length=50, null=True)),
                ('segment_1', models.CharField(max_length=50, null=True)),
                ('segment_2', models.CharField(max_length=50, null=True)),
                ('segment_3', models.CharField(max_length=50, null=True)),
                ('segment_4', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.GLIntegration')),
            ],
        ),
    ]
