# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-01-06 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20191222_1401'),
        ('accounting', '0027_glintegration_glintegrationdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='APGLIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100)),
                ('transaction_field', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ARGLIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100)),
                ('transaction_field', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ARGLIntegrationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_0', models.CharField(max_length=50, null=True)),
                ('segment_1', models.CharField(max_length=50, null=True)),
                ('segment_2', models.CharField(max_length=50, null=True)),
                ('segment_3', models.CharField(max_length=50, null=True)),
                ('segment_4', models.CharField(max_length=50, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.ARGLIntegration')),
            ],
        ),
        migrations.RenameModel(
            old_name='GLIntegrationDetail',
            new_name='APGLIntegrationDetail',
        ),
        migrations.RemoveField(
            model_name='glintegration',
            name='company',
        ),
        migrations.AlterField(
            model_name='apglintegrationdetail',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.APGLIntegration'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='document_type',
            field=models.CharField(choices=[('1', 'Invoice'), ('2', 'Debit Note'), ('3', 'Credit Note'), ('4', 'Interest'), ('5', 'Unapplied Cash'), ('6', 'Prepayment'), ('7', 'Receipt'), ('8', 'Refund'), ('9', 'Payment'), ('10', 'Adjustment'), ('11', 'Miscellaneous Receipt'), ('12', 'Miscellaneous Payment')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='journal',
            name='document_type',
            field=models.CharField(choices=[('1', 'Invoice'), ('2', 'Debit Note'), ('3', 'Credit Note'), ('4', 'Interest'), ('5', 'Unapplied Cash'), ('6', 'Prepayment'), ('7', 'Receipt'), ('8', 'Refund'), ('9', 'Payment'), ('10', 'Adjustment'), ('11', 'Miscellaneous Receipt'), ('12', 'Miscellaneous Payment')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='recurringentry',
            name='document_type',
            field=models.CharField(choices=[('1', 'Invoice'), ('2', 'Debit Note'), ('3', 'Credit Note'), ('4', 'Interest'), ('5', 'Unapplied Cash'), ('6', 'Prepayment'), ('7', 'Receipt'), ('8', 'Refund'), ('9', 'Payment'), ('10', 'Adjustment'), ('11', 'Miscellaneous Receipt'), ('12', 'Miscellaneous Payment')], default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='recurringentrydetail',
            name='document_type',
            field=models.CharField(choices=[('1', 'Invoice'), ('2', 'Debit Note'), ('3', 'Credit Note'), ('4', 'Interest'), ('5', 'Unapplied Cash'), ('6', 'Prepayment'), ('7', 'Receipt'), ('8', 'Refund'), ('9', 'Payment'), ('10', 'Adjustment'), ('11', 'Miscellaneous Receipt'), ('12', 'Miscellaneous Payment')], default='0', max_length=2),
        ),
        migrations.DeleteModel(
            name='GLIntegration',
        ),
    ]
