# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-02-20 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_auto_20200106_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='orig_exch_rate',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=20),
        ),
    ]
