# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-02-24 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20191222_1401'),
        ('accounting', '0029_auto_20200220_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='AROptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='IN', max_length=6, null=True)),
                ('invoice_length', models.IntegerField(default=22, null=True)),
                ('invoice_next_number', models.IntegerField(default=1, null=True)),
                ('cnote_prefix', models.CharField(default='CN', max_length=6, null=True)),
                ('cnote_length', models.IntegerField(default=22, null=True)),
                ('cnote_next_number', models.IntegerField(default=1, null=True)),
                ('dnote_prefix', models.CharField(default='DN', max_length=6, null=True)),
                ('dnote_length', models.IntegerField(default=22, null=True)),
                ('dnote_next_number', models.IntegerField(default=1, null=True)),
                ('interest_prefix', models.CharField(default='INT', max_length=6, null=True)),
                ('interest_length', models.IntegerField(default=22, null=True)),
                ('interest_next_number', models.IntegerField(default=1, null=True)),
                ('recurring_prefix', models.CharField(default='RC', max_length=6, null=True)),
                ('recurring_length', models.IntegerField(default=22, null=True)),
                ('recurring_next_number', models.IntegerField(default=1, null=True)),
                ('prepayment_prefix', models.CharField(default='PP', max_length=6, null=True)),
                ('prepayment_length', models.IntegerField(default=22, null=True)),
                ('prepayment_next_number', models.IntegerField(default=1, null=True)),
                ('ucash_prefix', models.CharField(default='UC', max_length=6, null=True)),
                ('ucash_length', models.IntegerField(default=22, null=True)),
                ('ucash_next_number', models.IntegerField(default=1, null=True)),
                ('adjustment_prefix', models.CharField(default='AD', max_length=6, null=True)),
                ('adjustment_length', models.IntegerField(default=22, null=True)),
                ('adjustment_next_number', models.IntegerField(default=1, null=True)),
                ('receipt_prefix', models.CharField(default='PY', max_length=6, null=True)),
                ('receipt_length', models.IntegerField(default=22, null=True)),
                ('receipt_next_number', models.IntegerField(default=1, null=True)),
                ('refund_prefix', models.CharField(default='RF', max_length=6, null=True)),
                ('refund_length', models.IntegerField(default=22, null=True)),
                ('refund_next_number', models.IntegerField(default=1, null=True)),
                ('aging_period_1', models.IntegerField(default=31, null=True)),
                ('aging_period_2', models.IntegerField(default=61, null=True)),
                ('aging_period_3', models.IntegerField(default=91, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
