# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-02-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20191222_1401'),
        ('accounting', '0031_apoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcode',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
        migrations.AddField(
            model_name='paymentcode',
            name='source_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
