# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-03-19 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_auto_20200227_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='customer_unapplied',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='journal',
            name='receipt_unapplied',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
