# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-12 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_auto_20200326_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='fully_paid_date',
            field=models.DateField(null=True),
        ),
    ]
