# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-04-26 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_journal_fully_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='error_entry',
            field=models.IntegerField(default=0),
        ),
    ]
