# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-06-15 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_auto_20200514_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='journal',
            name='orig_exch_rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='recurringentry',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='recurringentry',
            name='orig_exch_rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='recurringentrydetail',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='revaluationdetails',
            name='prior_rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='revaluationdetails',
            name='rev_rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='revaluationlogs',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
