# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-11-11 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_auto_20200615_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringentry',
            name='customer_unapplied',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='receipt_unapplied',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
