# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-01-06 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_auto_20201209_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
