# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_auto_20210106_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringentrydetail',
            name='is_manual_tax_input',
            field=models.BooleanField(default=False),
        ),
    ]
