# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-23 03:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20200601_1337'),
        ('currencies', '0006_exchangerate_apply_flag'),
        ('accounting', '0045_auto_20210818_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, null=True)),
                ('batch_date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(max_length=250, null=True)),
                ('batch_type', models.IntegerField(default=0)),
                ('document_type', models.CharField(choices=[('1', 'Invoice'), ('2', 'Debit Note'), ('3', 'Credit Note'), ('4', 'Interest'), ('5', 'Unapplied Cash'), ('6', 'Prepayment'), ('7', 'Receipt'), ('8', 'Refund'), ('9', 'Payment'), ('10', 'Adjustment'), ('11', 'Miscellaneous Receipt'), ('12', 'Miscellaneous Payment')], default='0', max_length=2)),
                ('no_entries', models.IntegerField(default=0)),
                ('batch_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('input_type', models.CharField(choices=[('1', 'Generated'), ('2', 'Manual Entry'), ('3', 'Imported')], default='0', max_length=2)),
                ('posting_sequence', models.CharField(max_length=50, null=True)),
                ('status', models.IntegerField(default=0)),
                ('update_date', models.DateField(auto_now=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('related_batch_id', models.IntegerField(default=0)),
                ('source_ledger', models.CharField(choices=[('SP', 'Sales & Purchase'), ('INV', 'Inventory'), ('AR', 'Account Receivable'), ('AP', 'Account Payable'), ('GL', 'General Ledger'), ('NOL', 'Undefined')], max_length=50, null=True)),
                ('flag', models.CharField(choices=[(0, 'UNMARKED'), (1, 'CHECKED'), (2, 'MODIFIED')], default=0, max_length=1)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
            ],
        ),
        migrations.AddField(
            model_name='recurringentry',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.RecurringBatch'),
        ),
    ]
