# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-08-26 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_auto_20210823_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringentrydetail',
            name='is_auto_exch',
            field=models.BooleanField(default=True),
        ),
    ]
