# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2021-10-20 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_recurringentrydetail_is_auto_exch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='document_number',
            field=models.CharField(db_index=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(default='', max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='order_number',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='po_number',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
