# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2022-03-27 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0051_journal_real_outstanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='real_discount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
