# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180215_1454'),
        ('accounting', '0003_auto_20180215_1454'),
        ('items', '0002_item_default_location'),
        ('countries', '0001_initial'),
        ('companies', '0002_auto_20180215_1454'),
        ('taxes', '0001_initial'),
        ('currencies', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('address', models.TextField(null=True)),
                ('postal_code', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('fax', models.CharField(max_length=20, null=True)),
                ('term_days', models.CharField(max_length=10, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=6, default=0, max_digits=20, null=True)),
                ('ship_via', models.CharField(default=0, max_length=500, null=True)),
                ('accode_ap', models.CharField(default=0, max_length=20, null=True)),
                ('accode_pur', models.CharField(default=0, max_length=20, null=True)),
                ('accode_exc', models.CharField(default=0, max_length=20, null=True)),
                ('accode_bnk', models.CharField(default=0, max_length=20, null=True)),
                ('accode_chr', models.CharField(default=0, max_length=20, null=True)),
                ('center_ap', models.CharField(default=0, max_length=20, null=True)),
                ('center_pur', models.CharField(default=0, max_length=20, null=True)),
                ('center_exc', models.CharField(default=0, max_length=20, null=True)),
                ('center_bnk', models.CharField(default=0, max_length=20, null=True)),
                ('center_chr', models.CharField(default=0, max_length=20, null=True)),
                ('ship_info_1', models.TextField(null=True)),
                ('ship_info_2', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('email_msg', models.CharField(default='                                                                    COMPANY_NAME\n\n\nDATE\n\n\nDear VENDOR_NAME,\n\nEnclosed please find our check as payment on our account.\nIf you have any questions regarding the payment, please call our accounting department at COMPANY_PHONE\nYours Sincerely,\nCOMPANY_NAME\n\n\n\nManager\nAccounts Payable\n\n', max_length=1000, null=True)),
                ('account_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.AccountSet')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
                ('distribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.DistributionCode')),
                ('payment_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.PaymentCode')),
                ('payment_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.TransactionMethod')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxes.Tax')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('purchase_price', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('new_price', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('leading_days', models.CharField(max_length=500, null=True)),
                ('effective_date', models.DateField(null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier')),
            ],
        ),
    ]
