# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-03-09 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_auto_20200309_1646'),
        ('suppliers', '0002_auto_20190730_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banks.Bank'),
        ),
    ]
