# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-03-26 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
