# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-05-13 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_auto_20200326_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
