# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

import companies.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('company_number', models.CharField(max_length=10, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('postal_code', models.CharField(max_length=10, null=True)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('web', models.CharField(max_length=500, null=True)),
                ('fax', models.CharField(max_length=20, null=True)),
                ('logo', models.ImageField(null=True, upload_to=companies.models.content_file_name)),
                ('header_logo', models.ImageField(null=True, upload_to=companies.models.content_file_name)),
                ('footer_logo', models.ImageField(null=True, upload_to=companies.models.content_file_name)),
                ('closing_date', models.DateField(null=True)),
                ('fiscal_period', models.DateField(null=True)),
                ('current_period_month', models.CharField(max_length=2, null=True)),
                ('current_period_year', models.CharField(max_length=4, null=True)),
                ('is_inventory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField()),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('code_size', models.CharField(max_length=2, null=True)),
                ('category_size', models.CharField(max_length=2, null=True)),
                ('extent_item', models.CharField(max_length=2, null=True)),
                ('group_item', models.CharField(max_length=2, null=True)),
                ('uom_item', models.CharField(max_length=10, null=True)),
                ('stock_take', models.CharField(max_length=10, null=True)),
                ('price_decimal', models.CharField(max_length=10, null=True)),
                ('cost_method', models.CharField(max_length=2, null=True)),
                ('remit_remark', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField()),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
