# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-19 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20180215_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='copy_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_copy_from', to='companies.Company'),
        ),
    ]
