# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-20 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20180215_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='use_segment',
            field=models.BooleanField(default=False),
        ),
    ]
