# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-27 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_copy_from'),
        ('companies', '0003_company_use_segment'),
    ]

    operations = [
    ]
