# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-10-11 04:17
from __future__ import unicode_literals

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bs_template',
            field=models.FileField(null=True, upload_to=companies.models.bs_template_container),
        ),
        migrations.AddField(
            model_name='company',
            name='pl_template',
            field=models.FileField(null=True, upload_to=companies.models.pl_template_container),
        ),
    ]
