# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-12-22 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20191011_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fiscal_period_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='gain_loss_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_multicurrency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='rate_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
