# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-06-01 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20191222_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_period_month_ic',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='current_period_month_sp',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='current_period_year_ic',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='current_period_year_sp',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
