# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-07-21 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191221_1245'),
        ('banks', '0005_auto_20200309_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='gain_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gain_account', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='bank',
            name='loss_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loss_account', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='bank',
            name='round_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_account', to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_account', to='accounts.Account'),
        ),
    ]
