# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-15 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('companies', '0002_auto_20180215_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=20, null=True)),
                ('attention', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('fax', models.CharField(max_length=20, null=True)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField()),
                ('pricing_type', models.CharField(choices=[('1', 'SIN $'), ('2', 'OTHERS')], max_length=2, null=True)),
                ('stock_class', models.CharField(choices=[('1', 'Internal Stock'), ('2', 'External Stock')], max_length=1, null=True)),
                ('stock_limit', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('stock_take_flag', models.CharField(max_length=50, null=True)),
                ('stock_take_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='LocationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onhand_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('onhand_amount', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('booked_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('booked_amount', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('cost_price', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('mv_cost_price', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('mv_cost_price_flag', models.CharField(max_length=50, null=True)),
                ('mv_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('in_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('out_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('min_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('max_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('reorder_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('back_order_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('stock_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('last_open_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('last_closing_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('month_open_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('month_closing_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('year_open_qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('update_date', models.DateField(default=datetime.date.today)),
                ('update_by', models.CharField(max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
        ),
    ]
