# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20190530_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationitem',
            name='in_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='locationitem',
            name='out_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='locationitem',
            name='po_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='locationitem',
            name='so_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
