# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-12 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20190606_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationitem',
            name='po_qty',
        ),
        migrations.RemoveField(
            model_name='locationitem',
            name='so_qty',
        ),
    ]
