# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-06-21 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20190612_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationitem',
            name='booked_amount',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='locationitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='locationitem',
            name='mv_cost_price',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='locationitem',
            name='onhand_amount',
            field=models.DecimalField(decimal_places=6, max_digits=20, null=True),
        ),
    ]
