from django.conf.urls import url

from accounts import views

urlpatterns = [
    url(r'^$', views.load_list, name='index'),
    url(r'^list/$', views.load_list, name='account_list'),
    url(r'^add/$', views.account_add, name='account_add'),
    url(r'^edit/(?P<account_id>\d+)/$', views.account_edit, name='account_edit'),
    url(r'^history/$', views.load_account_history_list, name='account_history_list_default'),
    url(r'^history/(?P<account_id>\d+)/$', views.load_account_history_list, name='account_history_list'),
    url(r'^history/pagination/$', views.AccountHistory__asJson, name='AccountHistory__asJson'),
    url(r'^delete/(?P<account_id>\d+)/$', views.account_delete, name='account_delete'),
    url(r'^type/list/$', views.load_type_list, name='account_type_list'),
    url(r'^type/add/$', views.account_type_add, name='account_type_add'),
    url(r'^type/edit/(?P<account_type_id>\d+)/$', views.account_type_edit, name='account_type_edit'),
    url(r'^type/delete/(?P<account_type_id>\d+)/$', views.account_type_delete, name='account_type_delete'),
    url(r'^type/list/pagination/$', views.AccountType__asJson, name='AccountType__asJson'),
    url(r'^list/pagination/$', views.Account__asJson, name='Account__asJson'),
    url(r'^dist-code/list/(?P<type>\d+)/$', views.load_dist_code_list, name='dist_code_list'),
    url(r'^dist-code/add/(?P<type>\d+)/$', views.dist_code_add, name='dist_code_add'),
    url(r'^dist-code/edit/(?P<dist_code_id>\d+)/$', views.dist_code_edit, name='dist_code_edit'),
    url(r'^dist-code/delete/(?P<dist_code_id>\d+)/$', views.dist_code_delete, name='dist_code_delete'),
    url(r'^dist-code/list/pagination/(?P<type>\d+)/$', views.DistributionCode__asJson, name='DistributionCode__asJson'),
    url(r'^transaction/(?P<account_id>\d+)/(?P<period>.*)/$', views.load_account_transaction_list, name='account_transaction_list'),
    url(r'^transaction/$', views.load_account_transaction_list, name='account_transaction_list_default'),
    url(r'^transaction/pagination$', views.AccountTransaction__asJson, name='AccountTransaction__asJson'),
    url(r'^account-set/list/(?P<account_set_type>\d+)/$', views.load_account_set_list, name='account_set_list'),
    url(r'^account-set/add/(?P<account_set_type>\d+)/$', views.account_set_add, name='account_set_add'),
    url(r'^account-set/edit/(?P<account_set_id>\d+)/$', views.account_set_edit, name='account_set_edit'),
    url(r'^account-set/delete/(?P<account_set_id>\d+)/$', views.account_set_delete, name='account_set_delete'),
    url(r'^account-set/list/pagination/(?P<account_set_type>\d+)/$', views.AccountSet__asJson,
        name='AccountSet__asJson'),
    url(r'^get_account_code_list/$', views.get_account_code_list, name='get_account_code_list'),
    url(r'^revaluation-code/list/$', views.revaluation_code_list, name='revaluation_code_list'),
    url(r'^revaluation-code/add/$', views.revaluation_code_add, name='revaluation_code_add'),
    url(r'^revaluation-code/edit/(?P<revaluation_code_id>\d+)/$', views.revaluation_code_edit, name='revaluation_code_edit'),
    url(r'^revaluation-code/delete/(?P<revaluation_code_id>\d+)/$', views.revaluation_code_delete, name='revaluation_code_delete'),
    url(r'^revaluation-code/list/pagination/$', views.RevaluationCode__asJson,
        name='RevaluationCode__asJson'),
    url(r'^load_account/$', views.load_account, name='load_account'),
    url(r'^detail_account/(?P<account_id>.*)/(?P<period>.*)/(?P<code>.*)/$', views.detail_account_json,
        name='detail_account_json'),
    url(r'^bycode_account/(?P<acc_code>.*)/(?P<period>.*)/(?P<res>.*)/$', views.bycode_account_json,
        name='bycode_account_json'),
    url(r'^report_account_group/(?P<active_tab_index>.*)/$', views.report_account_group, name='report_account_group'),
    url(r'^get_rpt_acc_grp/$', views.get_rpt_acc_grp, name='get_rpt_acc_grp'),
    url(r'^del_rpt_acc_grp/(?P<rpt_acc_grp_id>.*)/(?P<template_type>.*)/$', views.del_rpt_acc_grp,
        name='del_rpt_acc_grp'),
]
